[package]
name = "ruv-monitor-web"
version = "0.1.0"
edition = "2021"

[bin]
name = "ruv-monitor-web"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2"
yew = "0.20"
gloo-net = "0.2"
gloo-timers = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
